# Generated by Django 5.0.6 on 2024-06-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('categoria', models.CharField(max_length=60)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
