# Generated by Django 5.0.6 on 2024-07-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('categoria', models.CharField(max_length=60)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(default='', max_length=500)),
                ('imagen', models.ImageField(upload_to='productos')),
            ],
        ),
    ]
