# Generated by Django 5.0.1 on 2024-07-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_productos_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
