# Generated by Django 5.0.1 on 2024-07-03 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_productos_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='imagen',
        ),
    ]
