# Generated by Django 5.0.6 on 2024-07-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_carrito_carritoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
