# Generated by Django 5.0.6 on 2024-07-10 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_alter_carritoitem_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_tarjeta', models.CharField(max_length=16)),
                ('codigo_seg', models.CharField(max_length=3)),
                ('fecha_venc_mes', models.CharField(max_length=2)),
                ('fecha_venc_anno', models.CharField(max_length=2)),
                ('direccion', models.CharField(max_length=300)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
