# Generated by Django 5.0.6 on 2024-07-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_informacionusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='marca',
            field=models.CharField(default='', max_length=100),
        ),
    ]
